import { useEffect, useMemo, useRef, useState } from 'react'
import './restaurant-template.css'

export type RestaurantTemplateConfig = {
  name: string
  slug: string
  category: string
  palette: { primary: string; secondary: string; background: string; text: string }
}

const imagePool = [
  'photo-1504674900247-0877df9cc836', 'photo-1546069901-ba9599a7e63c', 'photo-1504674900247-0877df9cc836',
  'photo-1550547660-d9450f859349', 'photo-1555939594-58d7cb561ad1', 'photo-1509440159596-0249088772ff',
  'photo-1551024506-0bccd828d307', 'photo-1504674900247-0877df9cc836', 'photo-1504674900247-0877df9cc836',
  'photo-1517701604599-bb29b565090c', 'photo-1504674900247-0877df9cc836', 'photo-1504674900247-0877df9cc836',
  'photo-1504674900247-0877df9cc836', 'photo-1495474472287-4d71bcdd2085', 'photo-1517248135467-4c7edcad34c4',
]

const copy: Record<string, { kicker: string; title: string; text: string; menu: string[]; story: string; experience: string }> = {
  'bbq-grill': { kicker: 'Open fire. Honest food.', title: 'Fire. Smoke. Flavor.', text: 'Slow-smoked cuts, open-fire cooking and bold flavors made for unforgettable nights.', menu: ['Oak-Smoked Brisket', 'Charred Ribs', 'Fire-Grilled Chicken', 'Pepper Crust Short Rib'], story: 'We tend the coals, respect the clock, and serve barbecue with a little bit of swagger.', experience: 'The pit is the heart of the room. Gather close for smoke, stories and a table worth lingering at.' },
  pizza: { kicker: 'Dough made daily', title: 'A better kind of slice.', text: 'Naturally leavened dough, vivid ingredients and a blistering-hot oven.', menu: ['Margherita Verde', 'Spicy Pepperoni', 'Wild Mushroom', 'The House Pie'], story: 'Our dough gets the time it needs. The rest is a happy collision of heat, texture and tomato.', experience: 'Watch the oven work its magic, then pull up a chair while the next pie blisters.' },
  bakery: { kicker: 'Baked before sunrise', title: 'Made slowly. Shared warmly.', text: 'Hand-laminated pastries, soulful loaves and cakes for life’s good moments.', menu: ['Butter Croissant', 'Sourdough Loaf', 'Seasonal Tart', 'Cloud Cake'], story: 'Flour, butter, patience—and a neighborhood that knows the smell of fresh bread.', experience: 'From the first fold to the final glaze, every batch is made to make your day gentler.' },
  cafe: { kicker: 'Your daily pause', title: 'Find your favorite corner.', text: 'Thoughtful coffee, warm plates and the kind of room that makes time slow down.', menu: ['Velvet Flat White', 'Honey Toast', 'Garden Bowl', 'Afternoon Tonic'], story: 'A sunlit table, a familiar face, something excellent in your cup—that is our whole idea.', experience: 'Stay for one song or the whole afternoon. There is always another pot on.' },
  'fine-dining': { kicker: 'A table set for wonder', title: 'An evening, composed.', text: 'Seasonal ingredients become intimate, precise courses with a sense of place.', menu: ['Cured Hamachi', 'Truffle Consommé', 'Aged Duck', 'Dark Chocolate Silk'], story: 'We cook with restraint, curiosity and a belief that every course deserves its own small moment.', experience: 'A considered room, a generous pour and a menu that unfolds at its own pace.' },
  indian: { kicker: 'Rooted in spice', title: 'Tradition with a new rhythm.', text: 'Layered Indian flavors, live-fire technique and hospitality from the heart.', menu: ['Tandoori Cauliflower', 'Butter Chicken', 'Lamb Rogan Josh', 'Saffron Kulfi'], story: 'Recipes travel through generations. We keep their warmth and let them find new expression.', experience: 'Fragrant, vibrant and designed for sharing—this is a table with room for everyone.' },
  dessert: { kicker: 'Save room for joy', title: 'The sweet part starts here.', text: 'Small-batch desserts, bright fruit and a little theatre in every spoonful.', menu: ['Salted Caramel Sundae', 'Berry Pavlova', 'Chocolate Cloud', 'Pistachio Waffle'], story: 'We make desserts for celebrations, Tuesdays and every delicious thing in between.', experience: 'Choose your favorite, add a little extra, and stay long enough for a second look.' },
  'fast-food': { kicker: 'Made fast. Made fresh.', title: 'Big flavor, zero waiting.', text: 'Crisp, juicy, saucy food for people who know what they want.', menu: ['Double Stack Burger', 'Crispy Chicken', 'Loaded Fries', 'Shake of the Day'], story: 'We move quickly, source carefully and make every bite count.', experience: 'The grill is hot, the music is up and your order is almost ready.' },
  'cloud-kitchen': { kicker: 'Built for delivery', title: 'Kitchen-first. Crave-forward.', text: 'Freshly cooked comfort food designed to travel beautifully to your door.', menu: ['Crispy Rice Bowl', 'Miso Chicken Box', 'Chili Noodles', 'Midnight Cookie'], story: 'No dining room, no distractions—just a focused kitchen making food for your real life.', experience: 'Track your order from the wok to your doorstep, warm and right on time.' },
  'food-delivery': { kicker: 'Your neighborhood, delivered', title: 'What are you hungry for?', text: 'Discover local favorites, track every order and find a new go-to tonight.', menu: ['Neighborhood Picks', 'Fast & Fresh', 'Family Feasts', 'Sweet Endings'], story: 'The best meals live nearby. We make them easier to find and even easier to enjoy.', experience: 'Search, save, order and follow along—all in one deliciously simple place.' },
}

function Reveal({ children, className = '', id }: { children: React.ReactNode; className?: string; id?: string }) {
  const ref = useRef<HTMLElement>(null)
  useEffect(() => { const o = new IntersectionObserver(([e]) => e.isIntersecting && e.target.classList.add('rt-visible'), { threshold: .12 }); if (ref.current) o.observe(ref.current); return () => o.disconnect() }, [])
  return <section ref={ref} id={id} className={`rt-reveal ${className}`}>{children}</section>
}

export default function RestaurantTemplate({ config }: { config: RestaurantTemplateConfig }) {
  const [menu, setMenu] = useState(0); const [mobileOpen, setMobileOpen] = useState(false); const [lightbox, setLightbox] = useState<number | null>(null); const [sent, setSent] = useState(false)
  const content = copy[config.category] ?? copy.cafe
  const images = useMemo(() => { const n = [...config.slug].reduce((a, c) => a + c.charCodeAt(0), 0); return Array.from({ length: 10 }, (_, i) => `https://images.unsplash.com/${imagePool[(n + i * 3) % imagePool.length]}?auto=format&fit=crop&w=${i === 0 ? 1800 : 900}&q=85&sig=${n + i}`) }, [config.slug])
  const layout = useMemo(() => [...config.slug].reduce((a, c) => a + c.charCodeAt(0), 0) % 3, [config.slug])
  const categories = config.category === 'food-delivery' ? ['Popular', 'Near you', 'Under 30 min'] : ['Signatures', 'From the fire', 'Something sweet']
  const isDelivery = config.category === 'food-delivery' || config.category === 'cloud-kitchen'
  return <div className={`restaurant-template rt-${config.category} rt-layout-${layout}`} style={{ '--rt-primary': config.palette.primary, '--rt-secondary': config.palette.secondary, '--rt-bg': config.palette.background, '--rt-text': config.palette.text } as React.CSSProperties}>
    <div className="rt-announcement">{isDelivery ? 'Free delivery on your first order — use HELLO' : `${content.kicker} — reservations now open for the weekend`}</div>
    <header className="rt-nav"><a href="#top" className="rt-brand">{config.name}</a><button className="rt-mobile" aria-label="Toggle navigation" onClick={() => setMobileOpen(!mobileOpen)}>☰</button><nav className={mobileOpen ? 'open' : ''}><a href="#menu">Menu</a><a href="#story">Our story</a><a href="#gallery">Gallery</a><a href="#visit">Visit</a><a className="rt-nav-cta" href="#reserve">{isDelivery ? 'Order now' : 'Reserve a table'}</a></nav></header>
    <main id="top">
      <Reveal className="rt-hero"><img src={images[0]} alt={`${config.name} hero`} /><div className="rt-hero-shade"/><div className="rt-hero-copy"><p>{content.kicker}</p><h1>{content.title}</h1><span>{content.text}</span><div><a className="rt-button" href="#menu">{isDelivery ? 'Start an order' : 'Explore the menu'} <b>→</b></a><a className="rt-text-link" href="#story">Our story</a></div></div></Reveal>
      <Reveal className="rt-intro"><p className="rt-eyebrow">{isDelivery ? 'A better way to eat' : 'A table with a point of view'}</p><h2>{config.name} is more than a meal. It’s a feeling worth coming back for.</h2><div className="rt-stat-row"><span><b>4.9</b> guest rating</span><span><b>Fresh</b> every day</span><span><b>01–11pm</b> daily</span></div></Reveal>
      <Reveal className="rt-menu" ><div className="rt-section-head"><div><p className="rt-eyebrow">Taste the difference</p><h2>{isDelivery ? 'Find your next favorite' : 'Signature menu'}</h2></div><a href="#reserve">View full menu →</a></div><div className="rt-tabs">{categories.map((x,i)=><button className={menu===i?'active':''} onClick={()=>setMenu(i)} key={x}>{x}</button>)}</div><div className="rt-product-grid">{content.menu.map((name,i)=><article className="rt-product" key={`${menu}-${name}`}><img src={images[i+1]} alt={name}/><div><p>{i % 2 ? 'Chef’s choice' : 'House favorite'}</p><h3>{menu === 0 ? name : `${categories[menu]} ${name}`}</h3><span>{i % 2 ? 'Bright, generous and beautifully balanced.' : 'Made to order with serious care.'}</span><button onClick={() => alert(`${name} added to your order`)}>Add to order <b>+</b></button></div></article>)}</div></Reveal>
      <Reveal className="rt-split" id="story"><img src={images[5]} alt={`${config.name} kitchen`}/><div><p className="rt-eyebrow">Our story</p><h2>Made with purpose, served with heart.</h2><p>{content.story}</p><a className="rt-text-link" href="#visit">Meet the team →</a></div></Reveal>
      <Reveal className="rt-promo"><img src={images[6]} alt="Restaurant experience"/><div><p className="rt-eyebrow">The experience</p><h2>{content.experience}</h2><a className="rt-button light" href="#reserve">{isDelivery ? 'Browse restaurants' : 'Book your experience'} <b>→</b></a></div></Reveal>
      <Reveal className="rt-gallery" id="gallery"><div className="rt-section-head"><div><p className="rt-eyebrow">Through our lens</p><h2>Good moments, well fed.</h2></div><span>Tap an image to expand</span></div><div className="rt-gallery-grid">{images.slice(2,8).map((image,i)=><button key={image} onClick={()=>setLightbox(i+2)}><img src={image} alt={`${config.name} gallery ${i+1}`}/><span>View moment ↗</span></button>)}</div></Reveal>
      <Reveal className="rt-testimonials"><p className="rt-eyebrow">The word on the table</p><h2>Guests leave happy. Then they bring friends.</h2><div>{['“The kind of place you immediately want to tell people about.”','“Every detail felt easy, warm and genuinely delicious.”','“A new ritual for our whole group.”'].map((quote,i)=><blockquote key={quote}><p>{quote}</p><footer>★★★★★ <span>{['Mira S.','Aarav K.','Leah R.'][i]}</span></footer></blockquote>)}</div></Reveal>
      <Reveal className="rt-reserve" id="reserve"><div><p className="rt-eyebrow">{isDelivery ? 'Dinner, solved' : 'Make it a date'}</p><h2>{isDelivery ? 'A great meal is only a few taps away.' : 'Save your seat at the table.'}</h2><p>Choose a time, invite your people, and we’ll take care of the rest.</p></div><form onSubmit={e=>{e.preventDefault(); setSent(true)}}>{sent ? <strong>Perfect — we’ll be in touch shortly.</strong> : <><input aria-label="Your email" type="email" required placeholder="Your email address"/><button className="rt-button">{isDelivery ? 'Get offers' : 'Request a table'} <b>→</b></button></>}</form></Reveal>
      <Reveal className="rt-visit" id="visit"><img src={images[8]} alt={`${config.name} dining room`}/><div><p className="rt-eyebrow">Come say hello</p><h2>Find us where the good things happen.</h2><p>18 Market Lane, City Centre<br/>Monday–Sunday · 11am–11pm<br/>(555) 017-2026</p><a className="rt-text-link" href="https://maps.google.com" target="_blank" rel="noreferrer">Get directions →</a></div></Reveal>
    </main>
    <footer className="rt-footer"><div><strong>{config.name}</strong><p>{content.kicker}</p></div><div><a href="#menu">Menu</a><a href="#story">Story</a><a href="#gallery">Gallery</a><a href="#visit">Contact</a></div><p>© 2026 {config.name}. Made with good taste.</p></footer>
    {lightbox !== null && <div className="rt-lightbox" role="dialog" aria-modal="true" aria-label="Expanded gallery image" onClick={()=>setLightbox(null)}><button aria-label="Close image">×</button><img src={images[lightbox]} alt="Expanded gallery view"/></div>}
  </div>
}
