import { useMemo, useState } from 'react'
import './cafe-experience.css'

const options = { size: ['Small', 'Medium', 'Large'], milk: ['Whole', 'Oat', 'Almond'], extra: ['None', 'Extra shot', 'Vanilla'] }
const choices = { 'Strong & Bold': ['Double Espresso', 'Cold Brew'], 'Something Sweet': ['Vanilla Latte', 'Almond Croissant'], 'Light & Fresh': ['Iced Matcha', 'Lemon Loaf'], 'Cold & Refreshing': ['Nitro Cold Brew', 'Peach Fizz'] }
const locations = [['Willow Lane', '21 Willow Lane · 0.4 mi', '7:00 AM — 7:00 PM'], ['Market Hall', '8 Market Street · 1.1 mi', '8:00 AM — 6:00 PM']]

export default function CafeExperienceEnhancements({ themeName }: { themeName: string }) {
  const [size, setSize] = useState('Medium'); const [milk, setMilk] = useState('Oat'); const [extra, setExtra] = useState('None'); const [mood, setMood] = useState<keyof typeof choices>('Strong & Bold'); const [mode, setMode] = useState('Pickup'); const [location, setLocation] = useState(0); const [added, setAdded] = useState(false); const [confirmed, setConfirmed] = useState(false)
  const price = useMemo(() => 5.5 + (size === 'Large' ? 1 : size === 'Small' ? -.5 : 0) + (extra === 'Extra shot' ? 1 : extra === 'Vanilla' ? .5 : 0), [size, extra])
  return <>
    <section className="cafe-customizer"><div><span>MAKE IT YOURS</span><h2>Your perfect<br /><em>daily pour.</em></h2><p>Build a drink exactly how you like it—then add it to a demo order.</p></div><div className="cafe-builder"><strong>House latte <b>${price.toFixed(2)}</b></strong>{Object.entries(options).map(([label, values]) => <fieldset key={label}><legend>{label}</legend>{values.map(value => <button key={value} className={(label === 'size' ? size : label === 'milk' ? milk : extra) === value ? 'active' : ''} onClick={() => label === 'size' ? setSize(value) : label === 'milk' ? setMilk(value) : setExtra(value)}>{value}</button>)}</fieldset>)}<button className="cafe-primary" onClick={() => setAdded(true)}>{added ? 'Latte added to your demo order' : 'Add to order →'}</button></div></section>
    <section className="cafe-recommend"><span>DISCOVER YOUR NEXT FAVOURITE</span><h2>What are you in the mood for?</h2><div className="cafe-mood-controls">{Object.keys(choices).map(choice => <button key={choice} className={mood === choice ? 'active' : ''} onClick={() => setMood(choice as keyof typeof choices)}>{choice}</button>)}</div><p>Recommended for you</p><div className="cafe-recommendations">{choices[mood].map(item => <button key={item} onClick={() => setAdded(true)}>{item}<b>+</b></button>)}</div></section>
    <section className="cafe-seasonal"><div><span>SEASONAL FEATURE</span><h2>Made for<br /><em>this moment.</em></h2><p>A limited-run menu of considered flavours, available while the season lasts.</p></div><button onClick={() => document.getElementById('menu')?.scrollIntoView({ behavior: 'smooth' })}>Explore seasonal menu →</button></section>
    <section className="cafe-finder"><div><span>FIND YOUR CAFÉ</span><h2>Meet us around<br /><em>the corner.</em></h2>{locations.map((place, index) => <button key={place[0]} className={location === index ? 'active' : ''} onClick={() => setLocation(index)}><b>{place[0]}</b><small>{place[1]}</small></button>)}</div><aside><span>{themeName} · {mode}</span><h3>{locations[location][0]}</h3><p>{locations[location][1]}<br />Open {locations[location][2]}</p><div><button className={mode === 'Pickup' ? 'active' : ''} onClick={() => setMode('Pickup')}>Pickup</button><button className={mode === 'Dine in' ? 'active' : ''} onClick={() => setMode('Dine in')}>Dine in</button></div><button className="cafe-primary" onClick={() => setConfirmed(true)}>{confirmed ? 'Demo order confirmed.' : 'Confirm demo order →'}</button></aside></section>
  </>
}
